services:

#    student.example:
#        class: StudentBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    student.fixtures:
        class: StudentBundle\DataFixtures\StudentFixtures
        tags: ['doctrine.fixture.orm']
