<?php

namespace StudentBundle\Repository;

/**
 * StudentStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StudentStatusRepository extends \Doctrine\ORM\EntityRepository
{
}
