<?php

namespace StudentBundle\Repository;

/**
 * StudentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StudentRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @return mixed
     * @throws \Doctrine\ORM\NoResultException
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function getStudentsNumber()
    {
        $repo = $this->getEntityManager()->getRepository('StudentBundle:Student');
        $qb = $repo->createQueryBuilder('q');
        return $qb->select('count(q.id)')->getQuery()->getSingleScalarResult();
    }

}
